version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - backend
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb2:rw
    env_file:
      - ./env/influxdb.env

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    networks:
      - backend
    env_file:
      - ./env/zookeeper.env
    ports:
      - 22181:2181
    # volumes:
    #   - ./volumes/zookeeper/data:/var/lib/zookeeper/data
    #   - ./volumes/zookeeper/log:/var/lib/zookeeper/log

  kafka:
    container_name: kafka
    hostname: kafka
    # image: confluentinc/cp-kafka:latest
    build: kafka
    networks:
      - backend
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 29093:29093
    # volumes:
    #   - ./volumes/kafka:/var/lib/kafka/data
    env_file:
      - ./env/kafka.env

    healthcheck:
      test:
        ["CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 5s
      timeout: 10s
      retries: 20

  kafka_ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    networks:
      - backend
    ports:
      - 8080:8080
    depends_on:
      - kafka
    env_file:
      - ./env/kafka-ui.env

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
      - zookeeper
    networks:
      - backend
    volumes:
      # Mount for telegraf config
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - ./env/influxdb.env


  # chronograf:
  #   image: chronograf:latest
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./volumes/chronograf:/var/lib/chronograf
  #   depends_on:
  #     - influxdb
  #   environment:
  #     - INFLUXDB_URL=http://influxdb:8086
  #     - INFLUXDB_USERNAME=admin@gmail.com
  #     - INFLUXDB_PASSWORD=7cb4df40-5339-45b9-a812-4cc84ece400c
  #     - TOKEN_SECRET=2d6ca67a-f528-46ad-b548-0750d1379ed7
  #     - USE_V2_API=true
  #     - JWKS_URL=https://keycloak.bagiit.vn/realms/sap/protocol/openid-connect/certs
  #     - PUBLIC_URL=http://localhost:8888
  #     - GENERIC_CLIENT_ID=chronograf
  #     - GENERIC_CLIENT_SECRET=0JMTZhvx6mpBRPokClTxWwtTS6paX4DH
  #     - GENERIC_AUTH_URL=https://keycloak.bagiit.vn/realms/sap/protocol/openid-connect/auth
  #     - GENERIC_TOKEN_URL=https://keycloak.bagiit.vn/realms/sap/protocol/openid-connect/token
  #     - GENERIC_SCOPES=openid,profile,email
  #     - GENERIC_API_URL=https://keycloak.bagiit.vn/realms/sap/protocol/openid-connect/userinfo
  #     - "CUSTOM_LINKS=Keycloak Logout:https://keycloak.bagiit.vn/realms/sap/protocol/openid-connect/logout"
  # jobmanager:
  #   image: flink:latest
  #   ports:
  #     - "8081:8081"
  #   command: jobmanager
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager

  # taskmanager:
  #   image: flink:latest
  #   depends_on:
  #     - jobmanager
  #   command: taskmanager
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager

networks:
  backend:
    driver: bridge
    name: traffic-monitoring
