FROM node:20-alpine as base

FROM base as builder

WORKDIR /app

COPY . .

ENV PORT 5000

RUN npm i pnpm -g

RUN pnpm install

RUN pnpm build

RUN rm -rf node_modules

ENV NODE_ENV=production

RUN pnpm install --frozen-lockfile --prod

FROM base as runner

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 5000
CMD ["node", "dist/main.js"]